### ISSUE TITLE
Error: use of undeclared identifier 'HKCategoryValueSleepAnalysisAsleepCore'

### ISSUE THREAD

**Issue by ruchi-goyal** [agencyenterprise/react-native-health#267]
**Describe the bug**
error: duplicate case value 'HKCategoryValueSleepAnalysisAsleep'
error: use of undeclared identifier 'HKCategoryValueSleepAnalysisAsleepREM'; did you mean 'HKCategoryValueSleepAnalysisAsleep'?
error: use of undeclared identifier 'HKCategoryValueSleepAnalysisAsleepDeep'; did you mean 'HKCategoryValueSleepAnalysisAsleep'
error: use of undeclared identifier 'HKCategoryValueSleepAnalysisAsleepCore'; did you mean 'HKCategoryValueSleepAnalysisAsleep'

**To Reproduce**
Install 1.13.2 and build app

**Expected behavior**
Build should pass

**Additional context**
It is working correctly on 1.13.0 and not on latest patch version 1.13.2

**Comment by Gincioks** [comment]
Same for me.

**Comment by MUmer01** [comment]
Same

**Comment by GGGava** [comment]
Hello, you need to update your Xcode to >=14.0.0. If you cannot, I suggest commenting out these cases.
